language: c
dist: bionic

# build each debug level, to make sure they all work
env:
  - DEBUG=0 TARGET=Arduino
  - DEBUG=1 TARGET=Arduino
  - DEBUG=2 TARGET=Arduino
  - DEBUG=0 TARGET=DebugBoard09
  - DEBUG=1 TARGET=DebugBoard09
  - DEBUG=2 TARGET=DebugBoard09

before_install:
  - sudo apt-get update
  - sudo apt-get install -y gcc-avr binutils-avr avr-libc

script:
  - cd firmware
  - make DEBUG=$DEBUG TARGET=$TARGET